# Based off of https://github.com/actions/starter-workflows/blob/main/pages/hugo.yml
name: Deploy Hugo site to Pages

on:
  # Runs on pushes targeting the default branch.
  push:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages.
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run
# in-progress and latest queued. However, do NOT cancel in-progress runs as we
# want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

# Default to bash.
defaults:
  run:
    shell: bash

jobs:
  # Build job.
  build:
    runs-on: ubuntu-latest
    env:
      EMACS_VERSION: 29.4
      HUGO_VERSION: 0.132.2
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install Emacs ${{ env.EMACS_VERSION }}
        uses: purcell/setup-emacs@master
        with:
          version: ${{ env.EMACS_VERSION }}
      - name: Cache Emacs packages
        uses: actions/cache@v4
        with:
          path: content-org/.packages
          key: ${{ runner.os }}-emacs-${{ hashFiles('content-org/export.el') }}
      - name: Export Org Roam to Markdown
        run: make
      - name: Install Hugo ${{ env.HUGO_VERSION }}
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
            && sudo dpkg -i ${{ runner.temp }}/hugo.deb
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5
      - name: Build with Hugo
        env:
          HUGO_CACHEDIR: ${{ runner.temp }}/hugo_cache
          HUGO_ENVIRONMENT: production
        run: |
          hugo \
            --minify \
            --baseURL "${{ steps.pages.outputs.base_url }}/"
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  # Deployment job.
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
